In [1]:
import numpy as np
import random

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

np.random.seed(42)
random.seed(42)

from DataExploration import DataExploration
from DecisionTree import DecisionTree
from NeuralNetwork import DNN
from Boosting import Boosting
from KNN import KNN
from NeuralNetworkKeras import NN_Keras
from SVM import SVM

C:\Users\matan\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


C:\Users\matan\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Using TensorFlow backend.


In [2]:
# get datasets ready
de = DataExploration()

twitter_df = de.prepare_twitter_df()
speed_dating_df = de.prepare_speed_dating_df()
encoded_speed_dating_df, labelled_speed_dating_df, label_encoder = de.get_hot_encoded_speed_dating(speed_dating_df)

(22223, 10)


(19276, 10)
(41499, 10)


(8378, 44)
removing empty values shape:
(6794, 44)


In [3]:
X_train, X_test, y_train, y_test = de.get_train_test_validation(encoded_speed_dating_df, 'speed_dating')

In [4]:
# de.investigate_twitter(twitter_df)
# de.investigate_speed_dating(labelled_speed_dating_df, label_encoder)

['num_following', 'num_followers', 'num_tweets', 'len_of_screen_name', 'len_of_profile_description', 'num_following_changes']


C:\Users\matan\Anaconda3\lib\site-packages\scipy\stats\stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval


['num_following', 'num_followers', 'num_tweets', 'len_of_screen_name', 'len_of_profile_description', 'num_following_changes']


(6794, 44)
(array([3336.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
       3458.]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]), <a list of 10 Patch objects>)
(array([1675.,    0.,  340.,    0.,    0.,  503.,    0., 3824.,    0.,
        452.]), array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. ]), <a list of 10 Patch objects>)
(array([1641.,    0.,  355.,    0.,    0.,  556.,    0., 3795.,    0.,
        447.]), array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. ]), <a list of 10 Patch objects>)
(array([ 434.,  404.,  444.,  590.,  471.,  692.,  336., 1277., 1416.,
        730.]), array([  0. ,  24.7,  49.4,  74.1,  98.8, 123.5, 148.2, 172.9, 197.6,
       222.3, 247. ]), <a list of 10 Patch objects>)


C:\Users\matan\OneDrive\Documents\OMSCS\CS7641\assignments\code\CS7641-assignment1\DataExploration.py:230: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data_speed_dating['label'] = np.where(data_speed_dating['decision'] == 1, 'positive_date', 'negative_date')


['importance_same_race', 'importance_same_religion', 'field', 'attractive_important', 'sincere_important', 'intellicence_important', 'funny_important', 'ambtition_important', 'shared_interests_important', 'attractive', 'sincere', 'intelligence', 'funny', 'ambition', 'attractive_partner', 'sincere_partner', 'intelligence_partner', 'funny_partner', 'ambition_partner', 'shared_interests_partner', 'sports', 'tvsports', 'exercise', 'dining', 'museums', 'art', 'hiking', 'gaming', 'clubbing', 'reading', 'tv', 'theater', 'movies', 'concerts', 'music', 'shopping', 'yoga', 'interests_correlate']




# Speed Dating Learners


In [4]:
#best_params = {'dt__alpha': -0.01, 'dt__max_depth': 9, 'dt__min_samples_leaf': 7} #twitter
#best_params = {'dt__alpha': -0.1, 'dt__max_depth': 9, 'dt__min_samples_leaf': 2} #speed_dating  (CV score=0.724):
dt_clf = DecisionTree(model_name='dt_pruning_1', dataset_name='speed_dating')
dt_clf.train(X_train, y_train)
y_pred = dt_clf.predict(X_test)
dt_clf.evaluate_model(y_test=y_test, y_pred=y_pred)

#print(dt_clfr.get_model().best_estimator_.named_steps['dt'].tree_.max_depth)


In [ ]:
dt_best_params = dt_clf.get_best_params()
print(dt_best_params)
dt_clf_model = dt_clf.get_model()
#print(dt_clf.feature_importance_)


None


In [ ]:
#best_params = {'boost__base_estimator__max_depth': 12, 'boost__n_estimators': 80}
#best_params = {'boost__base_estimator__max_depth': 12, 'boost__n_estimators': 40} (CV score=0.772):
boosting_clf = Boosting(model_name='boosting_1', dataset_name='speed_dating')
boosting_clf.train(X_train, y_train)
y_pred = boosting_clf.predict(X_test)
boosting_clf.evaluate_model(y_test=y_test, y_pred=y_pred)


ValueError: Number of weights=3505 does not match number of samples=2804

In [ ]:
boosting_best_params = boosting_clf.get_best_params()
print(boosting_best_params)
boosting_clf_model = boosting_clf.get_model()

None


In [9]:
#best_params = {'knn__metric': 'manhattan', 'knn__n_neighbors': 10, 'knn__weights': 'distance'} #twitter
#{'knn__metric': 'manhattan', 'knn__n_neighbors': 121, 'knn__weights': 'distance'} (CV score=0.749): #speeddating
knn_clf = KNN(model_name='knn_1', dataset_name='speed_dating')
knn_clf.train(X_train, y_train)
y_pred = knn_clf.predict(X_test)
knn_clf.evaluate_model(y_test=y_test, y_pred=y_pred)


Best parameter (CV score=0.749):
{'knn__metric': 'manhattan', 'knn__n_neighbors': 121, 'knn__weights': 'distance'}


[[562  72]
 [189 273]]
             precision    recall  f1-score   support

        0.0       0.75      0.89      0.81       634
        1.0       0.79      0.59      0.68       462

avg / total       0.77      0.76      0.75      1096



In [10]:
knn_best_params = knn_clf.get_best_params()
print(knn_best_params)
knn_clf_model = knn_clf.get_model()

{'knn__metric': 'manhattan', 'knn__n_neighbors': 121, 'knn__weights': 'distance'}


In [11]:
#best_params = {'knn__metric': 'manhattan', 'knn__n_neighbors': 10, 'knn__weights': 'distance'} #twitter
#{'knn__metric': 'manhattan', 'knn__n_neighbors': 49, 'knn__weights': 'distance'} (CV score=0.728): #speeddating
knn_clf = KNN(model_name='knn_1', dataset_name='speed_dating')
knn_clf.train(X_train, y_train)
y_pred = knn_clf.predict(X_test)
knn_clf.evaluate_model(y_test=y_test, y_pred=y_pred)


Best parameter (CV score=0.749):
{'knn__metric': 'manhattan', 'knn__n_neighbors': 121, 'knn__weights': 'distance'}


[[562  72]
 [189 273]]
             precision    recall  f1-score   support

        0.0       0.75      0.89      0.81       634
        1.0       0.79      0.59      0.68       462

avg / total       0.77      0.76      0.75      1096



In [12]:
#best_params = {'knn__metric': 'manhattan', 'knn__n_neighbors': 10, 'knn__weights': 'distance'} #twitter
#{'knn__metric': 'manhattan', 'knn__n_neighbors': 49, 'knn__weights': 'distance'} (CV score=0.728): #speeddating
knn_clf = KNN(model_name='knn_1', dataset_name='speed_dating')
knn_clf.train(X_train, y_train)
y_pred = knn_clf.predict(X_test)
knn_clf.evaluate_model(y_test=y_test, y_pred=y_pred)


KeyboardInterrupt: 

In [13]:
#best_params = {'batch_size': 10, 'epochs': 1, 'layer_sizes': [12, 1], 'learning_rate': 0.0005,
#               'loss': 'mean_squared_error'}
#best_params = {'dnn__batch_size': 100, 'dnn__epochs': 50, 'dnn__layer_sizes': [180, 50], 'dnn__learning_rate': 0.0005, 'dnn__loss': 'mean_squared_error'} #
best_params = {'dnn__batch_size': 50, 'dnn__epochs': 30, 'dnn__layer_sizes': [100, 20], 'dnn__learning_rate': 0.0005, 'dnn__loss': 'binary_crossentropy'} #
keras_nn_clf = NN_Keras(model_name='keras_nn_1', dataset_name='speed_dating', best_params=best_params)
keras_nn_clf.train(X_train, y_train)
y_pred = keras_nn_clf.predict(X_test)
keras_nn_clf.evaluate_model(y_test=y_test, y_pred=y_pred)



Epoch 1/30


  50/4382 [..............................] - ETA: 1:00 - loss: 8.9277 - acc: 0.4400

 900/4382 [=====>........................] - ETA: 2s - loss: 9.5831 - acc: 0.3989  

1950/4382 [============>.................] - ETA: 0s - loss: 9.1321 - acc: 0.4272

3100/4382 [====================>.........] - ETA: 0s - loss: 9.0717 - acc: 0.4310

4300/4382 [============================>.] - ETA: 0s - loss: 9.0315 - acc: 0.4335

4382/4382 [==============================] - 1s 207us/step - loss: 9.0335 - acc: 0.4334


Epoch 2/30
  50/4382 [..............................] - ETA: 0s - loss: 8.9277 - acc: 0.4400

1350/4382 [========>.....................] - ETA: 0s - loss: 9.0694 - acc: 0.4311

2700/4382 [=================>............] - ETA: 0s - loss: 9.0517 - acc: 0.4322

3950/4382 [==========================>...] - ETA: 0s - loss: 9.0206 - acc: 0.4342

4382/4382 [==============================] - 0s 40us/step - loss: 9.0335 - acc: 0.4334


Epoch 3/30
  50/4382 [..............................] - ETA: 0s - loss: 9.5654 - acc: 0.4000

1300/4382 [=======>......................] - ETA: 0s - loss: 8.9155 - acc: 0.4408

2600/4382 [================>.............] - ETA: 0s - loss: 9.1791 - acc: 0.4242

3800/4382 [=========================>....] - ETA: 0s - loss: 9.0368 - acc: 0.4332

4382/4382 [==============================] - 0s 41us/step - loss: 9.0335 - acc: 0.4334


Epoch 4/30


  50/4382 [..............................] - ETA: 0s - loss: 9.5654 - acc: 0.4000

1350/4382 [========>.....................] - ETA: 0s - loss: 9.0813 - acc: 0.4304

2600/4382 [================>.............] - ETA: 0s - loss: 8.9339 - acc: 0.4396

3700/4382 [========================>.....] - ETA: 0s - loss: 9.0096 - acc: 0.4349

4382/4382 [==============================] - 0s 42us/step - loss: 9.0335 - acc: 0.4334


Epoch 5/30


  50/4382 [..............................] - ETA: 0s - loss: 10.2031 - acc: 0.3600

1300/4382 [=======>......................] - ETA: 0s - loss: 9.2098 - acc: 0.4223 

2550/4382 [================>.............] - ETA: 0s - loss: 9.1153 - acc: 0.4282

3900/4382 [=========================>....] - ETA: 0s - loss: 9.0095 - acc: 0.4349

4382/4382 [==============================] - 0s 42us/step - loss: 9.0335 - acc: 0.4334


Epoch 6/30
  50/4382 [..............................] - ETA: 0s - loss: 9.5654 - acc: 0.4000

1350/4382 [========>.....................] - ETA: 0s - loss: 9.0340 - acc: 0.4333

2750/4382 [=================>............] - ETA: 0s - loss: 8.9567 - acc: 0.4382

4250/4382 [============================>.] - ETA: 0s - loss: 9.0103 - acc: 0.4348

4382/4382 [==============================] - 0s 37us/step - loss: 9.0335 - acc: 0.4334


Epoch 7/30
  50/4382 [..............................] - ETA: 0s - loss: 10.8408 - acc: 0.3200

1350/4382 [========>.....................] - ETA: 0s - loss: 9.0340 - acc: 0.4333 

2650/4382 [=================>............] - ETA: 0s - loss: 9.1082 - acc: 0.4287

4000/4382 [==========================>...] - ETA: 0s - loss: 9.0353 - acc: 0.4332

4382/4382 [==============================] - 0s 39us/step - loss: 9.0335 - acc: 0.4334


Epoch 8/30
  50/4382 [..............................] - ETA: 0s - loss: 11.4785 - acc: 0.2800

1350/4382 [========>.....................] - ETA: 0s - loss: 9.0813 - acc: 0.4304 

2700/4382 [=================>............] - ETA: 0s - loss: 9.0635 - acc: 0.4315

4150/4382 [===========================>..] - ETA: 0s - loss: 9.0315 - acc: 0.4335

4382/4382 [==============================] - 0s 38us/step - loss: 9.0335 - acc: 0.4334


Epoch 9/30
  50/4382 [..............................] - ETA: 0s - loss: 10.5220 - acc: 0.3400

1550/4382 [=========>....................] - ETA: 0s - loss: 9.2877 - acc: 0.4174 

3050/4382 [===================>..........] - ETA: 0s - loss: 8.9800 - acc: 0.4367

4382/4382 [==============================] - 0s 34us/step - loss: 9.0335 - acc: 0.4334


Epoch 10/30
  50/4382 [..............................] - ETA: 0s - loss: 8.9277 - acc: 0.4400

1500/4382 [=========>....................] - ETA: 0s - loss: 8.9702 - acc: 0.4373

3000/4382 [===================>..........] - ETA: 0s - loss: 8.9596 - acc: 0.4380

4382/4382 [==============================] - 0s 34us/step - loss: 9.0335 - acc: 0.4334


Epoch 11/30
  50/4382 [..............................] - ETA: 0s - loss: 9.8843 - acc: 0.3800

1500/4382 [=========>....................] - ETA: 0s - loss: 8.7577 - acc: 0.4507

2350/4382 [===============>..............] - ETA: 0s - loss: 9.1245 - acc: 0.4277



2900/4382 [==================>...........] - ETA: 0s - loss: 9.1311 - acc: 0.4272

3650/4382 [=======================>......] - ETA: 0s - loss: 8.9845 - acc: 0.4364

4300/4382 [============================>.] - ETA: 0s - loss: 9.0390 - acc: 0.4330

4382/4382 [==============================] - 0s 61us/step - loss: 9.0335 - acc: 0.4334


Epoch 12/30
  50/4382 [..............................] - ETA: 0s - loss: 8.6089 - acc: 0.4600

 800/4382 [====>.........................] - ETA: 0s - loss: 9.1270 - acc: 0.4275

1500/4382 [=========>....................] - ETA: 0s - loss: 8.8959 - acc: 0.4420

2200/4382 [==============>...............] - ETA: 0s - loss: 9.0292 - acc: 0.4336

2950/4382 [===================>..........] - ETA: 0s - loss: 8.9494 - acc: 0.4386

3750/4382 [========================>.....] - ETA: 0s - loss: 9.0255 - acc: 0.4339

4250/4382 [============================>.] - ETA: 0s - loss: 9.0515 - acc: 0.4322

4382/4382 [==============================] - 0s 77us/step - loss: 9.0335 - acc: 0.4334


Epoch 13/30


  50/4382 [..............................] - ETA: 0s - loss: 8.9277 - acc: 0.4400

 800/4382 [====>.........................] - ETA: 0s - loss: 9.1270 - acc: 0.4275

1650/4382 [==========>...................] - ETA: 0s - loss: 9.1113 - acc: 0.4285

2500/4382 [================>.............] - ETA: 0s - loss: 9.0744 - acc: 0.4308

3400/4382 [======================>.......] - ETA: 0s - loss: 9.1247 - acc: 0.4276

4300/4382 [============================>.] - ETA: 0s - loss: 9.0649 - acc: 0.4314

4382/4382 [==============================] - 0s 63us/step - loss: 9.0335 - acc: 0.4334


Epoch 14/30
  50/4382 [..............................] - ETA: 0s - loss: 8.2900 - acc: 0.4800

 400/4382 [=>............................] - ETA: 0s - loss: 8.9277 - acc: 0.4400

1750/4382 [==========>...................] - ETA: 0s - loss: 8.9095 - acc: 0.4411

3100/4382 [====================>.........] - ETA: 0s - loss: 9.0357 - acc: 0.4332

4250/4382 [============================>.] - ETA: 0s - loss: 8.9803 - acc: 0.4367

4382/4382 [==============================] - 0s 52us/step - loss: 9.0335 - acc: 0.4334


Epoch 15/30
  50/4382 [..............................] - ETA: 0s - loss: 8.2900 - acc: 0.4800

 850/4382 [====>.........................] - ETA: 0s - loss: 8.7777 - acc: 0.4494

1700/4382 [==========>...................] - ETA: 0s - loss: 9.0403 - acc: 0.4329

2550/4382 [================>.............] - ETA: 0s - loss: 9.0778 - acc: 0.4306

3450/4382 [======================>.......] - ETA: 0s - loss: 9.0987 - acc: 0.4293

4350/4382 [============================>.] - ETA: 0s - loss: 9.0377 - acc: 0.4331

4382/4382 [==============================] - 0s 60us/step - loss: 9.0335 - acc: 0.4334


Epoch 16/30
  50/4382 [..............................] - ETA: 0s - loss: 7.9712 - acc: 0.5000

 900/4382 [=====>........................] - ETA: 0s - loss: 9.0872 - acc: 0.4300

1800/4382 [===========>..................] - ETA: 0s - loss: 9.0606 - acc: 0.4317

2850/4382 [==================>...........] - ETA: 0s - loss: 9.0620 - acc: 0.4316

3900/4382 [=========================>....] - ETA: 0s - loss: 9.0749 - acc: 0.4308

4382/4382 [==============================] - 0s 52us/step - loss: 9.0335 - acc: 0.4334


Epoch 17/30
  50/4382 [..............................] - ETA: 0s - loss: 7.6523 - acc: 0.5200

1150/4382 [======>.......................] - ETA: 0s - loss: 8.9277 - acc: 0.4400

2300/4382 [==============>...............] - ETA: 0s - loss: 8.9347 - acc: 0.4396

3500/4382 [======================>.......] - ETA: 0s - loss: 9.0325 - acc: 0.4334

4382/4382 [==============================] - 0s 44us/step - loss: 9.0335 - acc: 0.4334


Epoch 18/30
  50/4382 [..............................] - ETA: 0s - loss: 11.7974 - acc: 0.2600

1250/4382 [=======>......................] - ETA: 0s - loss: 9.0298 - acc: 0.4336 

2250/4382 [==============>...............] - ETA: 0s - loss: 9.1049 - acc: 0.4289

3200/4382 [====================>.........] - ETA: 0s - loss: 9.0573 - acc: 0.4319

4250/4382 [============================>.] - ETA: 0s - loss: 9.0553 - acc: 0.4320

4382/4382 [==============================] - 0s 49us/step - loss: 9.0335 - acc: 0.4334


Epoch 19/30
  50/4382 [..............................] - ETA: 0s - loss: 10.5220 - acc: 0.3400

1050/4382 [======>.......................] - ETA: 0s - loss: 8.8974 - acc: 0.4419 

2050/4382 [=============>................] - ETA: 0s - loss: 8.9355 - acc: 0.4395

3150/4382 [====================>.........] - ETA: 0s - loss: 8.9834 - acc: 0.4365

4150/4382 [===========================>..] - ETA: 0s - loss: 9.0315 - acc: 0.4335

4382/4382 [==============================] - 0s 51us/step - loss: 9.0335 - acc: 0.4334


Epoch 20/30
  50/4382 [..............................] - ETA: 0s - loss: 9.2466 - acc: 0.4200

1150/4382 [======>.......................] - ETA: 0s - loss: 8.7891 - acc: 0.4487

2300/4382 [==============>...............] - ETA: 0s - loss: 8.8792 - acc: 0.4430

3450/4382 [======================>.......] - ETA: 0s - loss: 8.9416 - acc: 0.4391

4382/4382 [==============================] - 0s 45us/step - loss: 9.0335 - acc: 0.4334


Epoch 21/30
  50/4382 [..............................] - ETA: 0s - loss: 6.6958 - acc: 0.5800

1100/4382 [======>.......................] - ETA: 0s - loss: 9.1451 - acc: 0.4264

2400/4382 [===============>..............] - ETA: 0s - loss: 9.1735 - acc: 0.4246

3750/4382 [========================>.....] - ETA: 0s - loss: 9.0808 - acc: 0.4304

4382/4382 [==============================] - 0s 42us/step - loss: 9.0335 - acc: 0.4334


Epoch 22/30
  50/4382 [..............................] - ETA: 0s - loss: 9.5654 - acc: 0.4000

1250/4382 [=======>......................] - ETA: 0s - loss: 8.9788 - acc: 0.4368



2500/4382 [================>.............] - ETA: 0s - loss: 8.8321 - acc: 0.4460

3700/4382 [========================>.....] - ETA: 0s - loss: 8.9364 - acc: 0.4395

4382/4382 [==============================] - 0s 42us/step - loss: 9.0335 - acc: 0.4334


Epoch 23/30
  50/4382 [..............................] - ETA: 0s - loss: 9.8843 - acc: 0.3800

1300/4382 [=======>......................] - ETA: 0s - loss: 8.9523 - acc: 0.4385

2650/4382 [=================>............] - ETA: 0s - loss: 9.0300 - acc: 0.4336

3950/4382 [==========================>...] - ETA: 0s - loss: 9.0125 - acc: 0.4347

4382/4382 [==============================] - 0s 41us/step - loss: 9.0335 - acc: 0.4334


Epoch 24/30


  50/4382 [..............................] - ETA: 0s - loss: 8.9277 - acc: 0.4400

1150/4382 [======>.......................] - ETA: 0s - loss: 9.0664 - acc: 0.4313

2450/4382 [===============>..............] - ETA: 0s - loss: 8.9733 - acc: 0.4371

3550/4382 [=======================>......] - ETA: 0s - loss: 9.1343 - acc: 0.4270

4382/4382 [==============================] - 0s 43us/step - loss: 9.0335 - acc: 0.4334


Epoch 25/30
  50/4382 [..............................] - ETA: 0s - loss: 7.9712 - acc: 0.5000

1200/4382 [=======>......................] - ETA: 0s - loss: 9.1403 - acc: 0.4267

1750/4382 [==========>...................] - ETA: 0s - loss: 9.1828 - acc: 0.4240

2550/4382 [================>.............] - ETA: 0s - loss: 9.1528 - acc: 0.4259

3550/4382 [=======================>......] - ETA: 0s - loss: 9.0355 - acc: 0.4332

4382/4382 [==============================] - 0s 62us/step - loss: 9.0335 - acc: 0.4334


Epoch 26/30
  50/4382 [..............................] - ETA: 0s - loss: 8.9277 - acc: 0.4400

 800/4382 [====>.........................] - ETA: 0s - loss: 9.2665 - acc: 0.4188

KeyboardInterrupt: 

In [14]:
keras_nn_best_params = keras_nn_clf.get_best_params()
print(keras_nn_best_params)

keras_nn_clf_model = keras_nn_clf.get_model()

{'dnn__batch_size': 50, 'dnn__epochs': 30, 'dnn__layer_sizes': [100, 20], 'dnn__learning_rate': 0.0005, 'dnn__loss': 'binary_crossentropy'}


In [15]:
#best_params = {'svm__C': 0.25, 'svm__degree': 1, 'svm__gamma': 0.25, 'svm__kernel': 'rbf'}
best_params = {'svm__C': 16.0, 'svm__gamma': 0.00390625, 'svm__kernel': 'rbf'} # (CV score=0.781)
svm_clf_rbf = SVM(model_name='svm_rbf_1', dataset_name='speed_dating', best_params=best_params)
svm_clf_rbf.train(X_train, y_train,'rbf')
y_pred = svm_clf_rbf.predict(X_test)
svm_clf_rbf.evaluate_model(y_test=y_test, y_pred=y_pred)


KeyboardInterrupt: 

In [16]:
svm_best_params = svm_clf_rbf.get_best_params()
print(svm_best_params) 
svm_clf_rbf_model = svm_clf_rbf.get_model()
#{'svm__degree': 1, 'svm__kernel': 'rbf'}
# (CV score=0.781):
# {'svm__C': 16.0, 'svm__gamma': 0.00390625, 'svm__kernel': 'rbf'}

{'svm__C': 16.0, 'svm__gamma': 0.00390625, 'svm__kernel': 'rbf'}


In [17]:
#best_params = {'svm__C': 0.25, 'svm__degree': 1, 'svm__gamma': 0.25, 'svm__kernel': 'rbf'}
best_params = {'svm__C': 0.0625, 'svm__gamma': 0.125, 'svm__kernel': 'poly'} #r (CV score=0.764):

svm_clf_poly = SVM(model_name='svm_poly_1', dataset_name='speed_dating', best_params=best_params)
svm_clf_poly.train(X_train, y_train,'poly')
y_pred = svm_clf_poly.predict(X_test)
svm_clf_poly.evaluate_model(y_test=y_test, y_pred=y_pred)


[[498 136]
 [131 331]]
             precision    recall  f1-score   support

        0.0       0.79      0.79      0.79       634
        1.0       0.71      0.72      0.71       462

avg / total       0.76      0.76      0.76      1096



In [18]:
svm_best_params = svm_clf_poly.get_best_params()
print(svm_best_params) 
svm_clf_poly_model = svm_clf_poly.get_model()
#{'svm__degree': 1, 'svm__kernel': 'rbf'}

{'svm__C': 0.0625, 'svm__gamma': 0.125, 'svm__kernel': 'poly'}


In [19]:
# #best_params = {'svm__C': 0.25, 'svm__degree': 1, 'svm__gamma': 0.25, 'svm__kernel': 'rbf'}
# #{'svm__C': 0.0625, 'svm__gamma': 0.125, 'svm__kernel': 'poly'} r (CV score=0.764):
# 
# svm_clf_linear_sigmoid = SVM(model_name='svm_linear_sigmoid_1', dataset_name='speed_dating')
# svm_clf_linear_sigmoid.train(X_train, y_train,'linear_sigmoid')
# y_pred = svm_clf_linear_sigmoid.predict(X_test)
# svm_clf_linear_sigmoid.evaluate_model(y_test=y_test, y_pred=y_pred)


In [20]:
# svm_best_params = svm_clf_linear_sigmoid.get_best_params()
# print(svm_best_params) 
# svm_clf_linear_sigmoid_model = svm_clf_linear_sigmoid.get_model()
# #{'svm__degree': 1, 'svm__kernel': 'rbf'}

# Twitter Learners

In [21]:
X_train, X_test, y_train, y_test, = de.get_train_test_validation(twitter_df, 'twitter')


ValueError: not enough values to unpack (expected 8, got 4)

In [22]:
#best_params = {'dt__alpha': -0.01, 'dt__max_depth': 9, 'dt__min_samples_leaf': 7} #twitter
#best_params = {'dt__alpha': -0.1, 'dt__max_depth': 9, 'dt__min_samples_leaf': 2} #speed_dating  (CV score=0.724):
dt_clf_t = DecisionTree(model_name='dt_pruning_1', dataset_name='twitter')
dt_clf_t.train(X_train, y_train)
y_pred = dt_clf_t.predict(X_test)
dt_clf_t.evaluate_model(y_test=y_test, y_pred=y_pred)

#print(dt_clfr.get_model().best_estimator_.named_steps['dt'].tree_.max_depth)


ValueError: Number of weights=3505 does not match number of samples=2804

In [23]:
dt_best_params = dt_clf_t.get_best_params()
print(dt_best_params)
dt_clf_t_model = dt_clf_t.get_model()
#print(dt_clf.feature_importance_)


None


In [24]:
#best_params = {'boost__base_estimator__max_depth': 12, 'boost__n_estimators': 80}
#best_params = {'boost__base_estimator__max_depth': 12, 'boost__n_estimators': 40} (CV score=0.772):
boosting_clf_t = Boosting(model_name='boosting_1', dataset_name='twitter')
boosting_clf_t.train(X_train, y_train)
y_pred = boosting_clf_t.predict(X_test)
boosting_clf_t.evaluate_model(y_test=y_test, y_pred=y_pred)


ValueError: Number of weights=3505 does not match number of samples=2804

In [25]:
boosting_best_params = boosting_clf_t.get_best_params()
print(boosting_best_params)
boosting_clf_t_model = boosting_clf.get_model()

None


In [26]:
#best_params = {'knn__metric': 'manhattan', 'knn__n_neighbors': 10, 'knn__weights': 'distance'} #twitter
#{'knn__metric': 'manhattan', 'knn__n_neighbors': 49, 'knn__weights': 'distance'} (CV score=0.728): #speeddating
knn_clf_t = KNN(model_name='knn_1', dataset_name='twitter')
knn_clf_t.train(X_train, y_train)
y_pred = knn_clf_t.predict(X_test)
knn_clf_t.evaluate_model(y_test=y_test, y_pred=y_pred)


In [ ]:
best_params = {'svm__C': 16.0, 'svm__gamma': 1.0, 'svm__kernel': 'rbf'}
svm_clf_rbf_t = SVM(model_name='svm_rbf_1', dataset_name='twitter', best_params=best_params)
svm_clf_rbf_t.train(X_train, y_train,'rbf')
y_pred = svm_clf_rbf_t.predict(X_test)
svm_clf_rbf_t.evaluate_model(y_test=y_test, y_pred=y_pred)

In [ ]:
svm_best_params = svm_clf_rbf_t.get_best_params()
print(svm_best_params) 
svm_clf_rbf_t_model = svm_clf_rbf_t.get_model()
#Best parameter (CV score=0.893):
#{'svm__C': 16.0, 'svm__gamma': 1.0, 'svm__kernel': 'rbf'}

In [ ]:
# #best_params = {'svm__C': 0.25, 'svm__degree': 1, 'svm__gamma': 0.25, 'svm__kernel': 'rbf'}
# #{'svm__C': 0.0625, 'svm__gamma': 0.125, 'svm__kernel': 'poly'} r (CV score=0.764):
# 
# svm_clf_poly = SVM(model_name='svm_wip_poly', dataset_name='twitter')
# svm_clf_poly.train(X_train, y_train,'poly')
# y_pred = svm_clf_poly.predict(X_test)
# svm_clf_poly.evaluate_model(y_test=y_test, y_pred=y_pred)


In [ ]:
# svm_best_params = svm_clf_poly.get_best_params()
# print(svm_best_params) 
# #{'svm__degree': 1, 'svm__kernel': 'rbf'}

In [ ]:
# #best_params = {'svm__C': 0.25, 'svm__degree': 1, 'svm__gamma': 0.25, 'svm__kernel': 'rbf'}
# #{'svm__C': 0.0625, 'svm__gamma': 0.125, 'svm__kernel': 'poly'} r (CV score=0.764):
# 
# svm_clf_linear_sigmoid = SVM(model_name='svm_wip_linear_sigmoid', dataset_name='twitter')
# svm_clf_linear_sigmoid.train(X_train, y_train,'linear_sigmoid')
# y_pred = svm_clf_linear_sigmoid.predict(X_test)
# svm_clf_linear_sigmoid.evaluate_model(y_test=y_test, y_pred=y_pred)


In [ ]:
# svm_best_params = svm_clf_linear_sigmoid.get_best_params()
# print(svm_best_params) 
# #{'svm__degree': 1, 'svm__kernel': 'rbf'}

In [ ]:
#best_params = {'batch_size': 10, 'epochs': 1, 'layer_sizes': [12, 1], 'learning_rate': 0.0005,
#               'loss': 'mean_squared_error'}
#{'dnn__batch_size': 10, 'dnn__epochs': 1, 'dnn__layer_sizes': [180, 50], 'dnn__learning_rate': 0.0005, 'dnn__loss': 'mean_squared_error'} #
keras_nn_clf = NN_Keras(model_name='keras_nn_wip1', dataset_name='spam_twitter')
keras_nn_clf.train(X_train, y_train)
y_pred = keras_nn_clf.predict(X_test)
keras_nn_clf.evaluate_model(y_test=y_test, y_pred=y_pred)


In [ ]:
keras_nn_best_params = keras_nn_clf.get_best_params()
print(keras_nn_best_params)